### ISSUE TITLE
Curl command for setting admin password broken in 6.0

### ISSUE THREAD

**Issue by bignastybryce** [tacitknowledge/aem-cookbook#19]
This one works, though:

curl -u admin:OLD PASSWORD -Fplain=NEW PASSWORD -Fverify=NEW PASSWORD  -Fold=OLD PASSWORD -FPath=/home/users/a/admin http://HOST:PORT/crx/explorer/ui/setpassword.jsp

**Comment by drewglass** [comment]
fixed in de8fb39e1cda28820ef0ba9a739728aa1fd16b30
