### ISSUE TITLE
Curl command for removing replicator agent broken

### ISSUE THREAD

**Issue by tmaier** [tacitknowledge/aem-cookbook#25]
https://github.com/tacitknowledge/aem-cookbook/blob/a43f1d38af4be1e60c706e68c7968ec4b8eb7efe/attributes/default.rb#L48

The following curl command is broken:

```erb
curl -u <%=local_user%>:<%=local_password%> -X DELETE http://localhost:<%=local_port%>/etc/replication/agents.<%=server%>/<%=h%>
```

it serializes the hash `h` on the end of the string (`<%=h%>`). This will lead to a failure on command execution.

**Comment by Psukhe** [comment]
That variable should be set via the provider on the following lines:
https://github.com/tacitknowledge/aem-cookbook/blob/master/providers/replicator.rb#L71-L80
Can you provide logs around this error?
Thanks,
-Alex

**Comment by Psukhe** [comment]
Looking into this more, I see  the issue you are pointing out. I think this should probably be set to <%=agent%><%=instance%> instead of <%=h%>
Sound right?
