### ISSUE TITLE
No resource or method named `aem_jar_installer' for `Chef::Recipe "author"

### ISSUE THREAD

**Issue by timdonovanuk** [tacitknowledge/aem-cookbook#5]
## NoMethodError

No resource or method named `aem_jar_installer' for`Chef::Recipe "author"'
## Cookbook Trace:

  /var/chef/site-cookbooks/aem-cookbook-master/recipes/author.rb:22:in `from_file'
## Relevant File Content:

/var/chef/site-cookbooks/aem-cookbook-master/recipes/author.rb:

 15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 16:  # See the License for the specific language governing permissions and
 17:  # limitations under the License.
 18:
 19:  include_recipe "aem::_base_aem_setup"
 20:
 21:  unless node[:aem][:use_yum]
 22>>   aem_jar_installer "author" do
 23:      download_url node[:aem][:download_url]
 24:      default_context node[:aem][:author][:default_context]
 25:      port node[:aem][:author][:port]
 26:      action :install
 27:    end
 28:  end
 29:
 30:  unless node[:aem][:license_url].nil?
 31:    remote_file "#{node[:aem][:author][:default_context]}/license.properties" do

Running handlers:
[2014-07-14T10:31:17+01:00] ERROR: Running exception handlers
Running handlers complete

[2014-07-14T10:31:17+01:00] ERROR: Exception handlers complete
[2014-07-14T10:31:17+01:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 1.906949103 seconds
[2014-07-14T10:31:17+01:00] ERROR: No resource or method named `aem_jar_installer' for`Chef::Recipe "author"'
[2014-07-14T10:31:17+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by pravrawa** [comment]
@Paul , I am still facing this issue.
https://github.com/tacitknowledge/aem-cookbook/issues/61
